services:
  document-converter-service:
    image: document-converter-service:0.0.8
    container_name: document-converter-service-test
    ports:
      - "8080:8080"
    environment:
      - DEBUG_MODE=true
    networks:
      - test-network
  jmeter:
    image: justb4/jmeter:5.5
    container_name: jmeter
    platform: linux/amd64
    user: root
    volumes:
      - ./jmeter-test:/jmeter
      - ./jmeter-test/dashboard:/jmeter/dashboard
    depends_on:
      - document-converter-service
    entrypoint: >
      /bin/sh -c "
      echo '🕓 Waiting for document-converter-service...';
      until curl -s http://document-converter-service:8080/actuator/health | grep 'UP' > /dev/null; do
        sleep 3;
      done;
      echo '✅ Service is up! Starting JMeter...';
      jmeter -n -t /jmeter/simple-mixed-load.jmx \
             -l /jmeter/results/simple-mixed-load-v0.0.8-results.jtl \
             -e -o /jmeter/dashboard"
    networks:
      - test-network

networks:
  test-network:
    name: test-network
