services:
  excel-to-pdf-service:
    image: excel-to-pdf-service:0.0.6
    container_name: excel-to-pdf-service-test
    ports:
      - "8080:8080"
    environment:
      - DEBUG_MODE=true
    networks:
      - test-network

  jmeter:
    image: justb4/jmeter:5.5
    container_name: jmeter
    user: root  
    volumes:
      - ./jmeter-test:/jmeter
    depends_on:
      - excel-to-pdf-service
    command: >
      -n -t /jmeter/optimized-mixed-load.jmx -l /jmeter/results/optimized-mixed-load-results.jtl -e -o /jmeter/dashboard
    networks:
      - test-network
      
networks:
  test-network:
    name: test-network
