version: '3.8'

services:
  excel-to-pdf-service:
    image: excel-to-pdf-service:0.0.1
    container_name: excel-to-pdf-service
    ports:
      - "8080:8080"
    environment:
      - DEBUG_MODE=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - test-network

  jmeter:
    image: justb4/jmeter:5.5
    container_name: jmeter
    user: root  
    volumes:
      - ./jmeter-test:/jmeter
    depends_on:
      - excel-to-pdf-service
    command: >
      -n -t /jmeter/excel-to-pdf-load-test.jmx 
      -l /jmeter/results/results.jtl 
      -e -o /jmeter/results/dashboard
    networks:
      - test-network

networks:
  test-network:
    name: test-network
